/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form_Presentation;

import DatabaseAccessObject_DAO.NhanVienDAO;
import DatabaseAccessObject_DAO.VaiTroDAO;
import Object_BusinessLogic.NhanVien;
import Object_BusinessLogic.VaiTro;
import java.awt.Component;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.ListCellRenderer;

/**
 *
 * @author Huynh
 */
public class Edit_Profile_Form extends javax.swing.JFrame {

    private NhanVien nhanVien;

    public NhanVien getNhanVien() {
        return nhanVien;
    }

    public void setNhanVien(NhanVien nhanVien) {
        this.nhanVien = nhanVien;
    }

    MAIN main;

    /**
     * Creates new form Edit_Profile_Form
     */
    public Edit_Profile_Form(MAIN m, NhanVien nv) {
        initComponents();
        this.setTitle("Edit Profile");
        this.main = m;
        txt_MaNhanVien.setEditable(false);
        txt_TaiKhoan.setEditable(false);
        loadCombobox_VaiTro();
        cbb_VaiTro.setEnabled(false);
        lbl_ngaySinh_Hint.setVisible(false);
        lbl_sdt_Hint.setVisible(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        txt_MaNhanVien.setText(nv.getMaNhanVien());
        txt_TenNhanVien.setText(nv.getHoTenNhanVien());
        txt_SDT.setText(nv.getSdt().toString());
        txt_DiaChi.setText(nv.getDiaChi());
        txt_Email.setText(nv.getEmail());
        txt_MatKhau.setText(nv.getMatKhau());
        txt_TaiKhoan.setText(nv.getTaiKhoan());
        date_ngaySinh.setDate(nv.getNgaySinh());
        if (nv.getGioiTinh().trim().equals("Nam")) {
            rbnNam.setSelected(true);
        } else {
            rbnNu.setSelected(true);
        }
    }

    public Edit_Profile_Form(NhanVien nv) {
        initComponents();
        this.setTitle("Edit Profile");
        txt_MaNhanVien.setEditable(false);
        txt_TaiKhoan.setEditable(false);
        loadCombobox_VaiTro();
        cbb_VaiTro.setEnabled(false);
        lbl_ngaySinh_Hint.setVisible(false);
        lbl_sdt_Hint.setVisible(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        txt_MaNhanVien.setText(nv.getMaNhanVien());
        txt_TenNhanVien.setText(nv.getHoTenNhanVien());
        txt_TenNhanVien.setEditable(false);
        txt_SDT.setText(nv.getSdt().toString());
        txt_SDT.setEditable(false);
        txt_DiaChi.setText(nv.getDiaChi());
        txt_DiaChi.setEditable(false);
        txt_Email.setText(nv.getEmail());
        txt_Email.setEditable(false);
        txt_MatKhau.setText(nv.getMatKhau());
        txt_MatKhau.setEditable(false);
        txt_TaiKhoan.setText(nv.getTaiKhoan());
        date_ngaySinh.setDate(nv.getNgaySinh());
        date_ngaySinh.setEnabled(false);
        if (nv.getGioiTinh().trim().equals("Nam")) {
            rbnNam.setSelected(true);
        } else {
            rbnNu.setSelected(true);
        }
        rbnNam.setEnabled(false);
        rbnNu.setEnabled(false);
        btn_Luu.setEnabled(false);
        btnXoaTrang.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgGioiTinh = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_MaNhanVien = new javax.swing.JTextField();
        btn_Luu = new javax.swing.JButton();
        btnXoaTrang = new javax.swing.JButton();
        txt_TenNhanVien = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbb_VaiTro = new javax.swing.JComboBox();
        txt_DiaChi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_SDT = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_Email = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        rbnNam = new javax.swing.JRadioButton();
        rbnNu = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        txt_TaiKhoan = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lbl_ngaySinh_Hint = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        date_ngaySinh = new com.toedter.calendar.JDateChooser();
        txt_MatKhau = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        lbl_sdt_Hint = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Profile", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Staff ID*");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 30, 110, 17);

        txt_MaNhanVien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txt_MaNhanVien);
        txt_MaNhanVien.setBounds(172, 27, 270, 30);

        btn_Luu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_Luu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-stock-save-as-icon.png"))); // NOI18N
        btn_Luu.setText("Save");
        btn_Luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LuuActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Luu);
        btn_Luu.setBounds(540, 280, 120, 43);

        btnXoaTrang.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnXoaTrang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-edit-clear-icon.png"))); // NOI18N
        btnXoaTrang.setText("Clear");
        btnXoaTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTrangActionPerformed(evt);
            }
        });
        jPanel1.add(btnXoaTrang);
        btnXoaTrang.setBounds(680, 280, 120, 43);

        txt_TenNhanVien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txt_TenNhanVien);
        txt_TenNhanVien.setBounds(172, 72, 270, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Staff Name*");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 75, 110, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Position*");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(480, 79, 123, 17);

        cbb_VaiTro.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbb_VaiTro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbb_VaiTro);
        cbb_VaiTro.setBounds(610, 70, 220, 30);

        txt_DiaChi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txt_DiaChi);
        txt_DiaChi.setBounds(172, 295, 270, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Address");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 298, 50, 17);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Gender*");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(480, 30, 70, 22);

        txt_SDT.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txt_SDT);
        txt_SDT.setBounds(172, 187, 270, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Phone Number*");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 193, 110, 17);

        txt_Email.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txt_Email);
        txt_Email.setBounds(172, 250, 270, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Email");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 255, 60, 17);

        bgGioiTinh.add(rbnNam);
        rbnNam.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rbnNam.setText("Male");
        jPanel1.add(rbnNam);
        rbnNam.setBounds(610, 20, 63, 39);

        bgGioiTinh.add(rbnNu);
        rbnNu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rbnNu.setText("Female");
        jPanel1.add(rbnNu);
        rbnNu.setBounds(700, 20, 80, 39);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Date Of Birth*");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 125, 120, 17);

        txt_TaiKhoan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txt_TaiKhoan);
        txt_TaiKhoan.setBounds(610, 120, 220, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Account Name*");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(480, 126, 100, 17);

        lbl_ngaySinh_Hint.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lbl_ngaySinh_Hint.setForeground(new java.awt.Color(204, 51, 0));
        lbl_ngaySinh_Hint.setText(" Invalid!");
        jPanel1.add(lbl_ngaySinh_Hint);
        lbl_ngaySinh_Hint.setBounds(172, 153, 130, 20);

        jLabel18.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel18.setText("(*) required fields");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(40, 330, 113, 26);

        date_ngaySinh.setDateFormatString("dd, MMMMMMMMMMMM, yyyy");
        date_ngaySinh.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(date_ngaySinh);
        date_ngaySinh.setBounds(172, 120, 270, 30);

        txt_MatKhau.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txt_MatKhau);
        txt_MatKhau.setBounds(610, 187, 220, 30);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Password*");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(480, 193, 100, 17);

        lbl_sdt_Hint.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lbl_sdt_Hint.setForeground(new java.awt.Color(204, 51, 0));
        lbl_sdt_Hint.setText(" Invalid!");
        jPanel1.add(lbl_sdt_Hint);
        lbl_sdt_Hint.setBounds(172, 220, 130, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/e.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(6, 18, 838, 355);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_LuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LuuActionPerformed
        lbl_ngaySinh_Hint.setVisible(false);
        lbl_sdt_Hint.setVisible(false);
        String textOnJDateChooser = ((JTextField) date_ngaySinh.getDateEditor().getUiComponent()).getText();
        if (txt_TenNhanVien.getText().isEmpty() || (rbnNam.isSelected() == false
                && rbnNu.isSelected() == false) || txt_SDT.getText().isEmpty() || textOnJDateChooser.isEmpty()
                || cbb_VaiTro.getSelectedItem() == null || txt_TaiKhoan.getText().isEmpty() || txt_MatKhau.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all required fields(*) in the Information box");
            return;
        }
        if (date_ngaySinh.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Invalid!! \n"
                    + "Some fields are not allowed to contain letters or special characters");
            lbl_ngaySinh_Hint.setVisible(true);
            return;
        } else {
            lbl_ngaySinh_Hint.setVisible(false);
        }
        while (true) {
            try {
                Integer.parseInt(txt_SDT.getText().trim());
                lbl_sdt_Hint.setVisible(false);
                break;
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Invalid!! \n"
                        + "Some fields are not allowed to contain letters or special characters");
                lbl_sdt_Hint.setVisible(true);
                return;
            }
        }
        String gtinh = "Nữ";
        if (rbnNam.isSelected()) {
            gtinh = "Nam";
        }
        NhanVienDAO nhanVienDAO = new NhanVienDAO();
        NhanVien nv = new NhanVien();
        nv.setMaNhanVien(txt_MaNhanVien.getText().trim().toUpperCase());
        nv.setHoTenNhanVien(txt_TenNhanVien.getText());
        nv.setNgaySinh(date_ngaySinh.getDate());
        nv.setDiaChi(txt_DiaChi.getText());
        nv.setSdt(Integer.parseInt(txt_SDT.getText()));
        nv.setGioiTinh(gtinh);
        nv.setEmail(txt_Email.getText());
        nv.setMaVaiTro(((VaiTro) cbb_VaiTro.getSelectedItem()).getMaVaiTro());
        nv.setTenVaiTro(((VaiTro) cbb_VaiTro.getSelectedItem()).getTenVaiTro());
        nv.setTaiKhoan(txt_TaiKhoan.getText().trim());
        nv.setMatKhau(txt_MatKhau.getText().trim());
        nhanVienDAO.update(nv);
        JOptionPane.showMessageDialog(this, "Information saved !");
        setNhanVien((new NhanVienDAO()).getNVByID(txt_MaNhanVien.getText().trim()));
        main.loadInfoNV(getNhanVien());
    }//GEN-LAST:event_btn_LuuActionPerformed

    private void btnXoaTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTrangActionPerformed
        txt_TenNhanVien.setText("");
        date_ngaySinh.setDate(null);
        txt_DiaChi.setText("");
        txt_SDT.setText("");
        txt_Email.setText("");
        txt_TaiKhoan.setText("");
        txt_MatKhau.setText("");
        bgGioiTinh.clearSelection();
        lbl_ngaySinh_Hint.setVisible(false);
        lbl_sdt_Hint.setVisible(false);
    }//GEN-LAST:event_btnXoaTrangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit_Profile_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit_Profile_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit_Profile_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit_Profile_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Edit_Profile_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgGioiTinh;
    private javax.swing.JButton btnXoaTrang;
    private javax.swing.JButton btn_Luu;
    private javax.swing.JComboBox cbb_VaiTro;
    private com.toedter.calendar.JDateChooser date_ngaySinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_ngaySinh_Hint;
    private javax.swing.JLabel lbl_sdt_Hint;
    private javax.swing.JRadioButton rbnNam;
    private javax.swing.JRadioButton rbnNu;
    private javax.swing.JTextField txt_DiaChi;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_MaNhanVien;
    private javax.swing.JTextField txt_MatKhau;
    private javax.swing.JTextField txt_SDT;
    private javax.swing.JTextField txt_TaiKhoan;
    private javax.swing.JTextField txt_TenNhanVien;
    // End of variables declaration//GEN-END:variables
 private void loadCombobox_VaiTro() {
        VaiTroDAO vaiTroDAO = new VaiTroDAO();
        //lấy toàn bộ bảng nhà cung cấp
        List<VaiTro> vaiTroList = vaiTroDAO.selectAll();
        Vector v = new Vector(vaiTroList);
        //nvởi tạo dữ liệu cho combobox
        DefaultComboBoxModel dcbm = new DefaultComboBoxModel(v);
        cbb_VaiTro.setModel(dcbm);
        //giúp tạo combobox hiển thị tên vai trò
        cbb_VaiTro.setRenderer(new ListCellRenderer() {
            DefaultListCellRenderer dlcr = new DefaultListCellRenderer();

            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                // gọi method giống hệt method cần viết, truyền vào tham số y như nguyên
                JLabel label = (JLabel) dlcr.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value != null) {
                    label.setText(((VaiTro) value).getTenVaiTro());
                }
                return label;
            }
        });
    }
}
