/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form_Presentation;

import DatabaseAccessObject_DAO.ChiTietHoaDonDAO;
import DatabaseAccessObject_DAO.HoaDonDAO;
import DatabaseAccessObject_DAO.KhachHangDAO;
import DatabaseAccessObject_DAO.NhanVienDAO;
import DatabaseAccessObject_DAO.SanPhamDAO;
import Functions.pdf_Export;
import Object_BusinessLogic.ChiTietHoaDon;
import Object_BusinessLogic.HoaDon;
import Object_BusinessLogic.KhachHang;
import Object_BusinessLogic.NhanVien;
import Object_BusinessLogic.SanPham;
import java.awt.Component;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.ListCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Form_BaoCao extends javax.swing.JFrame {

    DefaultTableModel tableModel = new DefaultTableModel();
    DecimalFormat df = new DecimalFormat("#,###");
    NhanVien nhanVien;
    KhachHang khachHang;

    /**
     * Creates new form FrmNhomKhachHang
     */
    public Form_BaoCao() throws ClassNotFoundException, SQLException {
        initComponents();
        loadCombobox_KhachHang();
        cbb_KhachHang.setSelectedItem(null);
        loadCombobox_NhanVien();
        cbb_NhanVien.setSelectedItem(null);
        loadDataIntoTaBle_HoaDon();
        date_ngayBanHang.setEnabled(false);
        btn_ThongTinKhachHang.setToolTipText("Customer Information");
        btn_ThongTinNhanVien.setToolTipText("Sale Staff Information");
        btn_ThongTinSanPham.setToolTipText("Product Information");
        btn_export_pdf.setToolTipText("Export this bill to PDF");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        date_ngayBanHang = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_DiaChi = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_TenKhachHang = new javax.swing.JLabel();
        lbl_Sdt = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tab_ThongTinHangHoa = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;   //Disallow the editing of any cell
            }
        };
        jLabel22 = new javax.swing.JLabel();
        lbl_SoTienPhaiTra = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        lbl_NhanVienBanHang = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_SoHoaDon = new javax.swing.JLabel();
        lbl_MaKhachHang = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        btn_ThongTinNhanVien = new javax.swing.JButton();
        btn_ThongTinKhachHang = new javax.swing.JButton();
        lbl_ghiChu = new javax.swing.JLabel();
        lbl_ThanhToan = new javax.swing.JLabel();
        btn_ThongTinSanPham = new javax.swing.JButton();
        btn_export_pdf = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_danhSachHoaDon = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;   //Disallow the editing of any cell
            }
        };
        jLabel24 = new javax.swing.JLabel();
        lbl_DoanhThu = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lbl_SoLuongSP_BanRa = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        date_from = new com.toedter.calendar.JDateChooser();
        date_to = new com.toedter.calendar.JDateChooser();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        btn_BaoCao = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txt_Search_SoHoaDon = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cbb_KhachHang = new javax.swing.JComboBox();
        cbb_NhanVien = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        date_ngayBanHang_Search = new com.toedter.calendar.JDateChooser();
        btn_TimKiem = new javax.swing.JButton();
        btn_Search_Clear = new javax.swing.JButton();
        btn_List_HoaDon = new javax.swing.JButton();
        btn_List_HoaDon1 = new javax.swing.JButton();
        btn_refresh_cbb = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Bill Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(date_ngayBanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 87, 220, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("BILL OF SALE");
        jPanel9.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 19, 178, 51));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Date");
        jPanel9.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 93, 43, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Sale Staff");
        jPanel9.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 134, 81, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Customer Name:");
        jPanel9.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 170, 116, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Phone Number:");
        jPanel9.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 216, 116, -1));

        lbl_DiaChi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_DiaChi.setText("...");
        jPanel9.add(lbl_DiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 251, 312, 29));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Address:");
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 247, 103, 33));

        lbl_TenKhachHang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_TenKhachHang.setText("...");
        jPanel9.add(lbl_TenKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 164, 154, 29));

        lbl_Sdt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_Sdt.setText("...");
        jPanel9.add(lbl_Sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 210, 250, 33));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel21.setText("Payment:");
        jPanel9.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 295, 103, -1));

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Product Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        tab_ThongTinHangHoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tab_ThongTinHangHoa);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 384, 580, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel22.setText("Total:");
        jPanel9.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 610, 46, 33));

        lbl_SoTienPhaiTra.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_SoTienPhaiTra.setText("...");
        jPanel9.add(lbl_SoTienPhaiTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 612, 95, 29));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel23.setText("(VND)");
        jPanel9.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 610, 46, 33));

        lbl_NhanVienBanHang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_NhanVienBanHang.setText("...");
        jPanel9.add(lbl_NhanVienBanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 128, 220, 29));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Customer ID:");
        jPanel9.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 170, 96, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Bill No.:");
        jPanel9.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 25, -1, -1));

        lbl_SoHoaDon.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_SoHoaDon.setText("...");
        jPanel9.add(lbl_SoHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 39, 29));

        lbl_MaKhachHang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_MaKhachHang.setText("...");
        jPanel9.add(lbl_MaKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 164, 70, 29));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel28.setText("Note:");
        jPanel9.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 340, 103, -1));

        btn_ThongTinNhanVien.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_ThongTinNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-view-pim-contacts-icon.png"))); // NOI18N
        btn_ThongTinNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThongTinNhanVienActionPerformed(evt);
            }
        });
        jPanel9.add(btn_ThongTinNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 605, 50, 43));

        btn_ThongTinKhachHang.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_ThongTinKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Apps-preferences-desktop-user-icon.png"))); // NOI18N
        btn_ThongTinKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThongTinKhachHangActionPerformed(evt);
            }
        });
        jPanel9.add(btn_ThongTinKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 605, 50, 43));

        lbl_ghiChu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_ghiChu.setText("...");
        jPanel9.add(lbl_ghiChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 334, 312, 29));

        lbl_ThanhToan.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_ThanhToan.setText("...");
        jPanel9.add(lbl_ThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 289, 312, 29));

        btn_ThongTinSanPham.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_ThongTinSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shopping-basket-info-icon (1).png"))); // NOI18N
        btn_ThongTinSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThongTinSanPhamActionPerformed(evt);
            }
        });
        jPanel9.add(btn_ThongTinSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 605, 50, 43));

        btn_export_pdf.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_export_pdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/document-filetype-pdf-icon.png"))); // NOI18N
        btn_export_pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_export_pdfActionPerformed(evt);
            }
        });
        jPanel9.add(btn_export_pdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 605, 50, 43));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Bill List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        tab_danhSachHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tab_danhSachHoaDon);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel24.setText("Revenue:");

        lbl_DoanhThu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_DoanhThu.setText("...");

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel25.setText("Sales Volume:");

        lbl_SoLuongSP_BanRa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_SoLuongSP_BanRa.setText("...");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Report", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel26.setText("To:");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel27.setText("From:");

        btn_BaoCao.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_BaoCao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/analytics-icon.png"))); // NOI18N
        btn_BaoCao.setText("Report");
        btn_BaoCao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BaoCaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btn_BaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(71, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date_to, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(date_from, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(147, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(date_from, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(date_to, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btn_BaoCao, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(209, Short.MAX_VALUE)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Bill No.");

        txt_Search_SoHoaDon.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Customer");

        cbb_KhachHang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbb_KhachHang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbb_NhanVien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbb_NhanVien.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("Sale Staff");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Date");

        btn_TimKiem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_TimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search-b-icon.png"))); // NOI18N
        btn_TimKiem.setText("Search");
        btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemActionPerformed(evt);
            }
        });

        btn_Search_Clear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_Search_Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-edit-clear-icon.png"))); // NOI18N
        btn_Search_Clear.setText("Clear");
        btn_Search_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Search_ClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btn_Search_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbb_KhachHang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(cbb_NhanVien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(date_ngayBanHang_Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_Search_SoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(24, 24, 24))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel12))
                    .addComponent(txt_Search_SoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7))
                    .addComponent(date_ngayBanHang_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel16))
                    .addComponent(cbb_KhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel15))
                    .addComponent(cbb_NhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Search_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btn_List_HoaDon.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_List_HoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-view-calendar-list-icon.png"))); // NOI18N
        btn_List_HoaDon.setText("Bill List");
        btn_List_HoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_List_HoaDonActionPerformed(evt);
            }
        });

        btn_List_HoaDon1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_List_HoaDon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Problem-info-2-icon.png"))); // NOI18N
        btn_List_HoaDon1.setText("Details");
        btn_List_HoaDon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_List_HoaDon1ActionPerformed(evt);
            }
        });

        btn_refresh_cbb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_refresh_cbb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/system-software-update-icon.png"))); // NOI18N
        btn_refresh_cbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refresh_cbbActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel29.setText("(VND)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_refresh_cbb)
                                .addGap(18, 18, 18)
                                .addComponent(btn_List_HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_List_HoaDon1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl_SoLuongSP_BanRa, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl_DoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_List_HoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_refresh_cbb, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(lbl_SoLuongSP_BanRa, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_DoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(btn_List_HoaDon1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_List_HoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_List_HoaDonActionPerformed
        try {
            loadDataIntoTaBle_HoaDon();
            date_ngayBanHang.setDate(null);
            lbl_SoHoaDon.setText("...");
            lbl_TenKhachHang.setText("...");
            lbl_NhanVienBanHang.setText("...");
            lbl_ghiChu.setText("...");
            lbl_MaKhachHang.setText("...");
            lbl_Sdt.setText("...");
            lbl_DiaChi.setText("...");
            lbl_ThanhToan.setText("...");
            tab_ThongTinHangHoa.setModel(new DefaultTableModel());
            lbl_SoTienPhaiTra.setText("...");
            lbl_SoLuongSP_BanRa.setText("...");
            lbl_DoanhThu.setText("...");
            txt_Search_SoHoaDon.setText("");
            date_ngayBanHang_Search.setDate(null);
            cbb_KhachHang.setSelectedItem(null);
            cbb_NhanVien.setSelectedItem(null);
            date_from.setDate(null);
            date_to.setDate(null);
            DefaultTableModel dm = new DefaultTableModel();
            tab_ThongTinHangHoa.setModel(dm);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Form_BaoCao.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Form_BaoCao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_List_HoaDonActionPerformed

    private void btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemActionPerformed
        //spởi tạo lại model, xóa hết cột cũ dòng cũ đi
        tableModel = new DefaultTableModel();
        //tạo cột
        tableModel.addColumn("Bill No.");
        tableModel.addColumn("Created Date");
        tableModel.addColumn("Customer");
        tableModel.addColumn("Sales Staff");
        tableModel.addColumn("Payment");
        tableModel.addColumn("Total   (VND)");
        HoaDonDAO hoaDonDAO = new HoaDonDAO();
        //lấy ra thông tin tìm kiếm
        HoaDon hd = new HoaDon();
        String textOnJDateChooser = ((JTextField) date_ngayBanHang_Search.getDateEditor().getUiComponent()).getText();
        if (txt_Search_SoHoaDon.getText().trim().equals("") && cbb_NhanVien.getSelectedItem() == null
                && cbb_KhachHang.getSelectedItem() == null && textOnJDateChooser.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter information into the search box!", "Message", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        Integer soHoaDon = null;
        if (!txt_Search_SoHoaDon.getText().trim().equals("")) {
            while (true) {
                try {
                    soHoaDon = (Integer.parseInt(txt_Search_SoHoaDon.getText().trim()));
                    break;
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Informations entered is invalid!! \n"
                            + "Some fields are not allowed to contain letters or special characters");
                    return;
                }
            }
        }

        Date ngayLap = date_ngayBanHang_Search.getDate();
        hd.setSoHoaDon(soHoaDon);
        NhanVien nv = (NhanVien) cbb_NhanVien.getSelectedItem();
        hd.setMaNhanVien(nv != null ? nv.getMaNhanVien() : null);
        KhachHang kh = (KhachHang) cbb_KhachHang.getSelectedItem();
        hd.setMaKhachHang(kh != null ? kh.getMaKH() : null);
        List<HoaDon> hdList = hoaDonDAO.search(soHoaDon, ngayLap, nv, kh);
        for (HoaDon hoaDon : hdList) {
            Vector vector = new Vector();
            vector.add(hoaDon.getSoHoaDon());
            vector.add(hoaDon.getNgayLapHoaDon());
            vector.add(hoaDon.getHoTenKhachHang());
            vector.add(hoaDon.getHoTenNhanVien());
            vector.add(hoaDon.getHinhThucThanhToan());
            vector.add(df.format(hoaDon.getTongTien()));
            //tạo hàng
            tableModel.addRow(vector);
        }
        //đưa dữ liệu từ model vào bảng
        tab_danhSachHoaDon.setModel(tableModel);
    }//GEN-LAST:event_btn_TimKiemActionPerformed

    private void btn_Search_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Search_ClearActionPerformed
        // TODO add your handling code here:
        txt_Search_SoHoaDon.setText("");
        date_ngayBanHang_Search.setDate(null);
        cbb_KhachHang.setSelectedItem(null);
        cbb_NhanVien.setSelectedItem(null);
    }//GEN-LAST:event_btn_Search_ClearActionPerformed

    private void btn_BaoCaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BaoCaoActionPerformed
        // TODO add your handling code here:
        tableModel = new DefaultTableModel();
        //tạo cột
        tableModel.addColumn("Bill No.");
        tableModel.addColumn("Created Date");
        tableModel.addColumn("Customer");
        tableModel.addColumn("Sales Staff");
        tableModel.addColumn("Quantity");
        tableModel.addColumn("Payment");
        tableModel.addColumn("Total   (VND)");
        String dateFrom = ((JTextField) date_from.getDateEditor().getUiComponent()).getText();
        String dateTo = ((JTextField) date_to.getDateEditor().getUiComponent()).getText();
        if (dateFrom.isEmpty() && dateTo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Select Date!");
            return;
        }
        if (!dateFrom.isEmpty() && date_from.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Invalid!! \n"
                    + "Some fields are not allowed to contain letters or special characters");
            return;
        }
        if (!dateTo.isEmpty() && date_to.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Invalid!! \n"
                    + "Some fields are not allowed to contain letters or special characters");
            return;
        }
        HoaDonDAO hoaDonDAO = new HoaDonDAO();
        List<HoaDon> hdList = hoaDonDAO.report(date_from.getDate(), date_to.getDate());
        for (HoaDon hoaDon : hdList) {
            Vector vector = new Vector();
            Integer soLuong = 0;
            if (hoaDon != null) {
                List<ChiTietHoaDon> cthd = (new ChiTietHoaDonDAO()).getListChiTietHoaDon(hoaDon.getSoHoaDon());
                for (ChiTietHoaDon ct : cthd) {
                    soLuong += ct.getSoLuong();
                }
            }
            vector.add(hoaDon.getSoHoaDon());
            vector.add(hoaDon.getNgayLapHoaDon());
            vector.add(hoaDon.getHoTenKhachHang());
            vector.add(hoaDon.getHoTenNhanVien());
            vector.add(soLuong);
            vector.add(hoaDon.getHinhThucThanhToan());
            vector.add(df.format(hoaDon.getTongTien()));
            //tạo hàng
            tableModel.addRow(vector);
        }
        //đưa dữ liệu từ model vào bảng
        tab_danhSachHoaDon.setModel(tableModel);

        Integer tongSP = 0;
        Integer tongTien = 0;
        if (!hdList.isEmpty()) {
            for (int i = 0; i < tab_danhSachHoaDon.getRowCount(); i++) {
                tongSP += (Integer) tab_danhSachHoaDon.getValueAt(i, 4);
            }
        }
        for (HoaDon hd : hdList) {
            tongTien += hd.getTongTien();
        }
        lbl_SoLuongSP_BanRa.setText(tongSP.toString());
        lbl_DoanhThu.setText(df.format(tongTien));
        
    }//GEN-LAST:event_btn_BaoCaoActionPerformed

    private void btn_List_HoaDon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_List_HoaDon1ActionPerformed
        try {
            // TODO add your handling code here:
            int row = tab_danhSachHoaDon.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Select a bill!");
                return;
            }
            Integer soHoaDon = (Integer) tab_danhSachHoaDon.getValueAt(row, 0);
            HoaDon hd = (new HoaDonDAO()).getHoaDon(soHoaDon);
            KhachHang kh = (new KhachHangDAO()).getKHByID(hd.getMaKhachHang().trim());
            this.khachHang = kh;
            NhanVien nv = (new NhanVienDAO()).getNVByID(hd.getMaNhanVien().trim());
            this.nhanVien = nv;
            lbl_SoHoaDon.setText(soHoaDon.toString());
            date_ngayBanHang.setDate(hd.getNgayLapHoaDon());
            lbl_NhanVienBanHang.setText(nv.getHoTenNhanVien() + "   (" + nv.getMaNhanVien() + ")");
            lbl_TenKhachHang.setText(kh.getHoTenKH());
            lbl_MaKhachHang.setText(kh.getMaKH());
            lbl_Sdt.setText(kh.getSdt().toString());
            lbl_DiaChi.setText(kh.getDiachi());
            lbl_ThanhToan.setText(hd.getHinhThucThanhToan());
            lbl_ghiChu.setText(hd.getGhiChu());
            lbl_SoTienPhaiTra.setText(df.format(hd.getTongTien()));
            loadDataIntoTaBle_SanPham(soHoaDon);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Form_BaoCao.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Form_BaoCao.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_List_HoaDon1ActionPerformed

    private void btn_ThongTinNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThongTinNhanVienActionPerformed
        // TODO add your handling code here:
        if (lbl_SoHoaDon.getText().equals("...")) {
            JOptionPane.showMessageDialog(this, "Bill is empty!");
            return;
        }
        Edit_Profile_Form epf = new Edit_Profile_Form(this.nhanVien);
        epf.setTitle("Sale Staff Information");
        epf.setVisible(true);
    }//GEN-LAST:event_btn_ThongTinNhanVienActionPerformed

    private void btn_ThongTinKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThongTinKhachHangActionPerformed
        // TODO add your handling code here:
        if (lbl_SoHoaDon.getText().equals("...")) {
            JOptionPane.showMessageDialog(this, "Bill is empty!");
            return;
        }
        Form_ThongTinKhachHang fttkh = new Form_ThongTinKhachHang(khachHang);
        fttkh.setTitle("Customer Information");
        fttkh.setVisible(true);
    }//GEN-LAST:event_btn_ThongTinKhachHangActionPerformed

    private void btn_refresh_cbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refresh_cbbActionPerformed
        // TODO add your handling code here:
        Object obj1 = cbb_KhachHang.getSelectedItem();
        Object obj2 = cbb_NhanVien.getSelectedItem();
        loadCombobox_KhachHang();
        loadCombobox_NhanVien();
        cbb_KhachHang.setSelectedItem(obj1);
        cbb_NhanVien.setSelectedItem(obj2);
    }//GEN-LAST:event_btn_refresh_cbbActionPerformed

    private void btn_ThongTinSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThongTinSanPhamActionPerformed
        // TODO add your handling code here:
        int row = tab_ThongTinHangHoa.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select product!", "Message", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        String maSanPham = tab_ThongTinHangHoa.getValueAt(row, 0).toString().trim();
        SanPham sp = new SanPhamDAO().getSanPhamByID(maSanPham);
        Form_ThongTinSanPham fttsp = new Form_ThongTinSanPham(sp);
        fttsp.setTitle("Product Information");
        fttsp.setVisible(true);
        tab_ThongTinHangHoa.clearSelection();
        
    }//GEN-LAST:event_btn_ThongTinSanPhamActionPerformed
    
    Boolean done = false;
    private void btn_export_pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_export_pdfActionPerformed
        // TODO add your handling code here:
        if (done) {
            JOptionPane.showMessageDialog(this, "This bill already created!", "Meessage",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setApproveButtonText("Save");

            ArrayList<String> specialChars = new ArrayList();
            specialChars.addAll(Arrays.asList(">", "<", "|", "?", "*", "/", "\\", "\""));
            String path;
            int res = (fileChooser.showOpenDialog(this));
            if (res == JFileChooser.APPROVE_OPTION) {
                path = fileChooser.getSelectedFile().toString();
                String fileName = fileChooser.getSelectedFile().getName();
                System.out.println(path);
                System.out.println(fileName);
                for (String character : specialChars) {
                    if (fileName.contains(character)) {
                        JOptionPane.showMessageDialog(this, "Invalid file name or this file already exist!",
                                "Export Failed!", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                }
                path += ".pdf";
                Integer soHoaDon = Integer.parseInt(lbl_SoHoaDon.getText());
                // create bill
                new pdf_Export().billExportToPDF(soHoaDon, path);
                JOptionPane.showMessageDialog(this, "Bill successfully generated!",
                        "Done", JOptionPane.INFORMATION_MESSAGE);
            }
            done = true;
        }
    }//GEN-LAST:event_btn_export_pdfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_BaoCao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_BaoCao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_BaoCao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_BaoCao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and dikhlay the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Form_BaoCao().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Form_BaoCao.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Form_BaoCao.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BaoCao;
    private javax.swing.JButton btn_List_HoaDon;
    private javax.swing.JButton btn_List_HoaDon1;
    private javax.swing.JButton btn_Search_Clear;
    private javax.swing.JButton btn_ThongTinKhachHang;
    private javax.swing.JButton btn_ThongTinNhanVien;
    private javax.swing.JButton btn_ThongTinSanPham;
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.JButton btn_export_pdf;
    private javax.swing.JButton btn_refresh_cbb;
    private javax.swing.JComboBox cbb_KhachHang;
    private javax.swing.JComboBox cbb_NhanVien;
    private com.toedter.calendar.JDateChooser date_from;
    private com.toedter.calendar.JDateChooser date_ngayBanHang;
    private com.toedter.calendar.JDateChooser date_ngayBanHang_Search;
    private com.toedter.calendar.JDateChooser date_to;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_DiaChi;
    private javax.swing.JLabel lbl_DoanhThu;
    private javax.swing.JLabel lbl_MaKhachHang;
    private javax.swing.JLabel lbl_NhanVienBanHang;
    private javax.swing.JLabel lbl_Sdt;
    private javax.swing.JLabel lbl_SoHoaDon;
    private javax.swing.JLabel lbl_SoLuongSP_BanRa;
    private javax.swing.JLabel lbl_SoTienPhaiTra;
    private javax.swing.JLabel lbl_TenKhachHang;
    private javax.swing.JLabel lbl_ThanhToan;
    private javax.swing.JLabel lbl_ghiChu;
    private javax.swing.JTable tab_ThongTinHangHoa;
    private javax.swing.JTable tab_danhSachHoaDon;
    private javax.swing.JTextField txt_Search_SoHoaDon;
    // End of variables declaration//GEN-END:variables

    private void loadCombobox_KhachHang() {
        KhachHangDAO khachHangDAO = new KhachHangDAO();
        //lấy toàn bộ bảng nhà cung cấp
        List<KhachHang> khachHangList = khachHangDAO.selectAll();
        Vector v = new Vector(khachHangList);
        //spởi tạo dữ liệu cho combobox
        DefaultComboBoxModel dcbm = new DefaultComboBoxModel(v);
        cbb_KhachHang.setModel(dcbm);
        //giúp tạo combobox hiển thị tên vai trò
        cbb_KhachHang.setRenderer(new ListCellRenderer() {
            DefaultListCellRenderer dlcr = new DefaultListCellRenderer();

            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                // gọi method giống hệt method cần viết, truyền vào tham số y như nguyên
                JLabel label = (JLabel) dlcr.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value != null) {
                    label.setText(((KhachHang) value).getHoTenKH());
                }
                return label;
            }
        });
    }

    private void loadCombobox_NhanVien() {
        NhanVienDAO nhanVienDAO = new NhanVienDAO();
        //lấy toàn bộ bảng nhà cung cấp
        List<NhanVien> nhanVienList = nhanVienDAO.selectAll();
        Vector v = new Vector(nhanVienList);
        //spởi tạo dữ liệu cho combobox
        DefaultComboBoxModel dcbm = new DefaultComboBoxModel(v);
        cbb_NhanVien.setModel(dcbm);
        //giúp tạo combobox hiển thị tên vai trò
        cbb_NhanVien.setRenderer(new ListCellRenderer() {
            DefaultListCellRenderer dlcr = new DefaultListCellRenderer();

            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                // gọi method giống hệt method cần viết, truyền vào tham số y như nguyên
                JLabel label = (JLabel) dlcr.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value != null) {
                    label.setText(((NhanVien) value).getHoTenNhanVien());
                }
                return label;
            }
        });
    }

    private void loadDataIntoTaBle_HoaDon() throws ClassNotFoundException, SQLException {
        //khởi tạo lại model, xóa hết cột cũ dòng cũ đi
        tableModel = new DefaultTableModel();
        //tạo cột
        tableModel.addColumn("Bill No.");
        tableModel.addColumn("Created Date");
        tableModel.addColumn("Customer");
        tableModel.addColumn("Sales Staff");
        tableModel.addColumn("Payment");
        tableModel.addColumn("Total   (VND)");
        HoaDonDAO hoaDonDAO = new HoaDonDAO();
        //lấy ra toàn bộ vai trò
        List<HoaDon> hoaDonList = hoaDonDAO.selectAll();
        for (HoaDon hd : hoaDonList) {
            Vector vector = new Vector();
            vector.add(hd.getSoHoaDon());
            vector.add(hd.getNgayLapHoaDon());
            vector.add(hd.getHoTenKhachHang());
            vector.add(hd.getHoTenNhanVien());
            vector.add(hd.getHinhThucThanhToan());
            vector.add(df.format(hd.getTongTien()));
            //tạo hàng
            tableModel.addRow(vector);
        }
        //đưa dữ liệu từ model vào bảng
        tab_danhSachHoaDon.setModel(tableModel);
    }

    private void loadDataIntoTaBle_SanPham(Integer soHoaDon) throws ClassNotFoundException, SQLException {
        //khởi tạo lại model, xóa hết cột cũ dòng cũ đi
        tableModel = new DefaultTableModel();
        //tạo cột
        tableModel.addColumn("Product ID");
        tableModel.addColumn("Product Name");
        tableModel.addColumn("Unit");
        tableModel.addColumn("Price (VND)");
        tableModel.addColumn("Quantity");
        tableModel.addColumn("Amount");

        ChiTietHoaDonDAO cthdDAO = new ChiTietHoaDonDAO();
        //lấy ra toàn bộ vai trò
        List<ChiTietHoaDon> cthdList = cthdDAO.getListChiTietHoaDon(soHoaDon);
        for (ChiTietHoaDon cthd : cthdList) {
            Vector vector = new Vector();
            vector.add(cthd.getMaSanPham());
            vector.add(cthd.getTenSanPham());
            vector.add((new SanPhamDAO()).getSanPhamByID(cthd.getMaSanPham()).getDonViTinh());
            vector.add(cthd.getDonGiaSanPham());
            vector.add(cthd.getSoLuong());
            vector.add(df.format(cthd.getThanhTien()));
            //tạo hàng
            tableModel.addRow(vector);
        }
        //đưa dữ liệu từ model vào bảng
        tab_ThongTinHangHoa.setModel(tableModel);
    }
}
