/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form_Presentation;

import DatabaseAccessObject_DAO.NhanVienDAO;
import Object_BusinessLogic.NhanVien;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Huynh
 */
public class Form_Login extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Form_Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        lbl_Id_Hint.setVisible(false);
        lbl_PW_Hint.setVisible(false);
        this.setTitle("Login");
    }

    public Form_Login(String taiKhoan, String matKhau) {
        initComponents();
        this.setLocationRelativeTo(null);
        lbl_Id_Hint.setVisible(false);
        lbl_PW_Hint.setVisible(false);
        txtUsername.setText(taiKhoan);
        pfdPassword.setText(matKhau);
        this.setTitle("Login");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        lbnUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lbnPassword = new javax.swing.JLabel();
        pfdPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lbl_PW_Hint = new javax.swing.JLabel();
        lbl_Id_Hint = new javax.swing.JLabel();
        ckb_ghiNho = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenuItem1.setText("jMenuItem1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(51, 255, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Login"));
        jPanel2.setLayout(null);

        lbnUsername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbnUsername.setForeground(new java.awt.Color(255, 255, 0));
        lbnUsername.setText("Username:");
        jPanel2.add(lbnUsername);
        lbnUsername.setBounds(60, 50, 120, 30);

        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        jPanel2.add(txtUsername);
        txtUsername.setBounds(60, 80, 230, 30);

        lbnPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbnPassword.setForeground(new java.awt.Color(255, 255, 0));
        lbnPassword.setText("Password:");
        jPanel2.add(lbnPassword);
        lbnPassword.setBounds(60, 130, 120, 30);

        pfdPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pfdPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfdPasswordActionPerformed(evt);
            }
        });
        pfdPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pfdPasswordKeyPressed(evt);
            }
        });
        jPanel2.add(pfdPassword);
        pfdPassword.setBounds(60, 160, 230, 30);

        btnLogin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Login-icon (1).png"))); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        btnLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLoginKeyPressed(evt);
            }
        });
        jPanel2.add(btnLogin);
        btnLogin.setBounds(350, 60, 130, 43);

        btnAbout.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Microsoft-Info-icon (1).png"))); // NOI18N
        btnAbout.setText("My Team");
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });
        jPanel2.add(btnAbout);
        btnAbout.setBounds(350, 180, 130, 43);

        btnClear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete-icon.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel2.add(btnClear);
        btnClear.setBounds(350, 120, 130, 43);

        lbl_PW_Hint.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lbl_PW_Hint.setForeground(new java.awt.Color(102, 255, 204));
        lbl_PW_Hint.setText("Enter Password!");
        jPanel2.add(lbl_PW_Hint);
        lbl_PW_Hint.setBounds(60, 190, 150, 20);

        lbl_Id_Hint.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lbl_Id_Hint.setForeground(new java.awt.Color(51, 255, 204));
        lbl_Id_Hint.setText("Enter ID!");
        jPanel2.add(lbl_Id_Hint);
        lbl_Id_Hint.setBounds(60, 110, 150, 20);

        ckb_ghiNho.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ckb_ghiNho.setForeground(new java.awt.Color(255, 255, 255));
        ckb_ghiNho.setText("Remember Me");
        jPanel2.add(ckb_ghiNho);
        ckb_ghiNho.setBounds(60, 210, 200, 30);

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 44)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 102, 0));
        jLabel2.setText("Sign In");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(183, 14, 160, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/girl_sunset_hair_profile_97163_1920x1080.jpg"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 270);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String taiKhoan = txtUsername.getText().trim();
        String matKhau = pfdPassword.getText().trim();
        if (taiKhoan.isEmpty()) {
            lbl_Id_Hint.setVisible(true);
            return;

        }
        if (!taiKhoan.isEmpty() && matKhau.isEmpty()) {
            lbl_Id_Hint.setVisible(false);
            lbl_PW_Hint.setVisible(true);
            return;
        }
        lbl_Id_Hint.setVisible(false);
        lbl_PW_Hint.setVisible(false);
        NhanVienDAO nhanVienDAO = new NhanVienDAO();
        NhanVien nv = new NhanVien();
        nv = nhanVienDAO.dangNhap(nv, taiKhoan, matKhau);
        if (nv != null) {
            JOptionPane.showMessageDialog(this, "Successfully!!");
            nv = nhanVienDAO.getNVByID(nv.getMaNhanVien());
            if (!ckb_ghiNho.isSelected()) {
                nv.setMatKhau("");
            }
            MAIN f = new MAIN(nv);
            this.dispose();
            f.setLocationRelativeTo(null);
            f.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Incorrect username or password!!");
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void pfdPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfdPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfdPasswordActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        // TODO add your handling code here:
//        About_Me about_Me = new About_Me();
//        about_Me.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
//        about_Me.setLocationRelativeTo(null);
//        about_Me.setVisible(true);
    }//GEN-LAST:event_btnAboutActionPerformed

    private void btnLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLoginKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginKeyPressed

    private void pfdPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfdPasswordKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            String taiKhoan = txtUsername.getText().trim();
            String matKhau = pfdPassword.getText().trim();
            if (taiKhoan.isEmpty()) {
                lbl_Id_Hint.setVisible(true);
                return;

            }
            if (!taiKhoan.isEmpty() && matKhau.isEmpty()) {
                lbl_Id_Hint.setVisible(false);
                lbl_PW_Hint.setVisible(true);
                return;
            }
            lbl_Id_Hint.setVisible(false);
            lbl_PW_Hint.setVisible(false);
            NhanVienDAO nhanVienDAO = new NhanVienDAO();
            NhanVien nv = new NhanVien();
            nv = nhanVienDAO.dangNhap(nv, taiKhoan, matKhau);
            if (nv != null) {
                JOptionPane.showMessageDialog(this, "Successfully!!");
                nv = nhanVienDAO.getNVByID(nv.getMaNhanVien());
                if (!ckb_ghiNho.isSelected()) {
                    nv.setMatKhau("");
                }
                MAIN f = new MAIN(nv);
                this.dispose();
                f.setLocationRelativeTo(null);
                f.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Incorrect username or password!!");
            }
        }
    }//GEN-LAST:event_pfdPasswordKeyPressed

    public void clear() {
        txtUsername.setText("");
        pfdPassword.setText("");
        lbl_Id_Hint.setVisible(false);
        lbl_PW_Hint.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnLogin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox ckb_ghiNho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_Id_Hint;
    private javax.swing.JLabel lbl_PW_Hint;
    private javax.swing.JLabel lbnPassword;
    private javax.swing.JLabel lbnUsername;
    private javax.swing.JPasswordField pfdPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
