/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form_Presentation;

import DatabaseAccessObject_DAO.LoaiSanPhamDAO;
import DatabaseAccessObject_DAO.NhaCungCapDAO;
import Object_BusinessLogic.LoaiSanPham;
import Object_BusinessLogic.NhaCungCap;
import Object_BusinessLogic.SanPham;
import java.awt.Component;
import java.text.DecimalFormat;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.ListCellRenderer;

/**
 *
 * @author Huynh
 */
public class Form_ThongTinSanPham extends javax.swing.JFrame {


    /**
     * Creates new form Edit_Profile_Form
     */

    public Form_ThongTinSanPham(SanPham sp) {
        initComponents();
        txt_MaSanPham.setEditable(false);
        loadCombobox();
        cbb_LoaiSanPham.setEnabled(false);
        cbb_NhaCungCap.setEnabled(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        DecimalFormat df = new DecimalFormat("#,###");
        
        txt_MaSanPham.setText(sp.getMaSanPham());
        txt_TenSanPham.setText(sp.getTenSanPham());
        txt_TenSanPham.setEditable(false);
        txt_DonGia.setText(df.format(sp.getDonGia()));
        txt_DonGia.setEditable(false);
        txt_XuatXu.setText(sp.getXuatXu());
        txt_XuatXu.setEditable(false);
        txt_DonViTinh.setText(sp.getDonViTinh());
        txt_DonViTinh.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgGioiTinh = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_MaSanPham = new javax.swing.JTextField();
        txt_TenSanPham = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbb_LoaiSanPham = new javax.swing.JComboBox();
        txt_DonGia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_XuatXu = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_DonViTinh = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbb_NhaCungCap = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Product ID:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 30, 110, 17);

        txt_MaSanPham.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txt_MaSanPham);
        txt_MaSanPham.setBounds(172, 27, 270, 30);

        txt_TenSanPham.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txt_TenSanPham);
        txt_TenSanPham.setBounds(172, 72, 270, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Product Name:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 75, 110, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Product Type:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(490, 30, 123, 17);

        cbb_LoaiSanPham.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbb_LoaiSanPham.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbb_LoaiSanPham);
        cbb_LoaiSanPham.setBounds(620, 25, 220, 30);

        txt_DonGia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txt_DonGia);
        txt_DonGia.setBounds(170, 170, 270, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Unit Price (VND):");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 180, 110, 17);

        txt_XuatXu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txt_XuatXu);
        txt_XuatXu.setBounds(170, 220, 270, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Origin:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 220, 60, 17);

        txt_DonViTinh.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txt_DonViTinh);
        txt_DonViTinh.setBounds(172, 120, 270, 30);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Unit:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(40, 130, 100, 17);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Supplier:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(490, 80, 123, 17);

        cbb_NhaCungCap.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbb_NhaCungCap.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbb_NhaCungCap);
        cbb_NhaCungCap.setBounds(620, 70, 220, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/e.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(6, 18, 838, 250);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_ThongTinSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_ThongTinSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_ThongTinSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_ThongTinSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Edit_Profile_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgGioiTinh;
    private javax.swing.JComboBox cbb_LoaiSanPham;
    private javax.swing.JComboBox cbb_NhaCungCap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_DonGia;
    private javax.swing.JTextField txt_DonViTinh;
    private javax.swing.JTextField txt_MaSanPham;
    private javax.swing.JTextField txt_TenSanPham;
    private javax.swing.JTextField txt_XuatXu;
    // End of variables declaration//GEN-END:variables
 private void loadCombobox() {
        LoaiSanPhamDAO lspdao = new LoaiSanPhamDAO();
        //lấy toàn bộ bảng nhà cung cấp
        List<LoaiSanPham> lspList = lspdao.selectAll();
        Vector v = new Vector(lspList);
        //nvởi tạo dữ liệu cho combobox
        DefaultComboBoxModel dcbm = new DefaultComboBoxModel(v);
        cbb_LoaiSanPham.setModel(dcbm);
        //giúp tạo combobox hiển thị tên vai trò
        cbb_LoaiSanPham.setRenderer(new ListCellRenderer() {
            DefaultListCellRenderer dlcr = new DefaultListCellRenderer();

            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                // gọi method giống hệt method cần viết, truyền vào tham số y như nguyên
                JLabel label = (JLabel) dlcr.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value != null) {
                    label.setText(((LoaiSanPham) value).getTenLoaiSP());
                }
                return label;
            }
        });
        
        //set cbb nhà cung cấp
        v = new Vector(new NhaCungCapDAO().selectAll());
        dcbm = new DefaultComboBoxModel(v);
        cbb_NhaCungCap.setModel(dcbm);
        //giúp tạo combobox hiển thị tên vai trò
        cbb_NhaCungCap.setRenderer(new ListCellRenderer() {
            DefaultListCellRenderer dlcr = new DefaultListCellRenderer();

            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                // gọi method giống hệt method cần viết, truyền vào tham số y như nguyên
                JLabel label = (JLabel) dlcr.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value != null) {
                    label.setText(((NhaCungCap) value).getTenNhaCC());
                }
                return label;
            }
        });
    }
}
