/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form_Presentation;

import DatabaseAccessObject_DAO.NhaCungCapDAO;
import DatabaseAccessObject_DAO.SanPhamDAO;
import Object_BusinessLogic.NhaCungCap;
import java.sql.SQLException;
import java.util.List;
import java.util.Random;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.OK_CANCEL_OPTION;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class FormNhaCungCap extends javax.swing.JFrame {

    DefaultTableModel tableModel = new DefaultTableModel();

    /**
     * Creates new form FrmNhomKhachHang
     */
    public FormNhaCungCap() throws ClassNotFoundException, SQLException {
        initComponents();
        loadDataIntoTable_NhaCC();
        lbl_maNhaCC_Hint.setVisible(false);
        lbl_sdt_Hint.setVisible(false);
        lbl_maNhaCC_Search_Hint.setVisible(false);
        lbl_sdt_Search_Hint.setVisible(false);
    }

    private void loadDataIntoTable_NhaCC() throws ClassNotFoundException, SQLException {
        //nccởi tạo lại model, xóa hết cột cũ dòng cũ đi
        tableModel = new DefaultTableModel();
        //tạo cột
        tableModel.addColumn("Supplier No.");
        tableModel.addColumn("Supplier Name");
        tableModel.addColumn("Phone Number");
        tableModel.addColumn("Email");
        tableModel.addColumn("Address");
        NhaCungCapDAO nhaCungCapDAO = new NhaCungCapDAO();
        //lấy ra toàn bộ vai trò
        List<NhaCungCap> nhaCungCapList = nhaCungCapDAO.selectAll();
        for (NhaCungCap ncc : nhaCungCapList) {
            Vector vector = new Vector();
            vector.add(ncc.getMaNhaCC());
            vector.add(ncc.getTenNhaCC());
            vector.add(ncc.getSdt());
            vector.add(ncc.getEmail());
            vector.add(ncc.getDiaChi());
            //tạo hàng
            tableModel.addRow(vector);
        }
        //đưa dữ liệu từ model vào bảng
        tab_NhaCungCap.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_MaNhaCC = new javax.swing.JTextField();
        btnSua = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnXoaTrang = new javax.swing.JButton();
        txt_TenNCC = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_DiaChi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_Email = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txt_Search_TenNhaCC = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_Search_NCC_ID = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        btn_Search_Clear = new javax.swing.JButton();
        lbl_maNhaCC_Search_Hint = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txt_Search_sdt = new javax.swing.JTextField();
        lbl_sdt_Search_Hint = new javax.swing.JLabel();
        lbl_maNhaCC_Hint = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbl_sdt_Hint = new javax.swing.JLabel();
        txt_SDT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_NhaCungCap = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;   //Disallow the editing of any cell
            }
        };
        btn_ListKH = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Supplier No.*");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 30, 130, 17);

        txt_MaNhaCC.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txt_MaNhaCC);
        txt_MaNhaCC.setBounds(170, 27, 410, 30);

        btnSua.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/system-software-update-icon.png"))); // NOI18N
        btnSua.setText("Update");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSua);
        btnSua.setBounds(369, 350, 120, 43);

        btnThem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Sign-Add-icon.png"))); // NOI18N
        btnThem.setText("Add");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel1.add(btnThem);
        btnThem.setBounds(209, 350, 120, 43);

        btnXoa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/trash-icon.png"))); // NOI18N
        btnXoa.setText("Delete");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel1.add(btnXoa);
        btnXoa.setBounds(528, 350, 120, 43);

        btnXoaTrang.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnXoaTrang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-edit-clear-icon.png"))); // NOI18N
        btnXoaTrang.setText("Clear");
        btnXoaTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTrangActionPerformed(evt);
            }
        });
        jPanel1.add(btnXoaTrang);
        btnXoaTrang.setBounds(688, 350, 120, 43);

        txt_TenNCC.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txt_TenNCC);
        txt_TenNCC.setBounds(170, 96, 410, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Supplier Name*");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 100, 140, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Email");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 231, 123, 17);

        txt_DiaChi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txt_DiaChi);
        txt_DiaChi.setBounds(170, 290, 410, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Address");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 290, 70, 17);

        txt_Email.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txt_Email);
        txt_Email.setBounds(170, 225, 410, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Phone Number*");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 155, 130, 17);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Search"));
        jPanel3.setForeground(new java.awt.Color(0, 204, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel12.setText("Supplier Name");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 97, -1, -1));

        txt_Search_TenNhaCC.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel3.add(txt_Search_TenNhaCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 220, 30));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setText("Supplier No.");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 37, 124, -1));

        txt_Search_NCC_ID.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel3.add(txt_Search_NCC_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 220, 30));

        btnTimKiem.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/search-b-icon.png"))); // NOI18N
        btnTimKiem.setText("Search");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        jPanel3.add(btnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, 43));

        btn_Search_Clear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_Search_Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-edit-clear-icon.png"))); // NOI18N
        btn_Search_Clear.setText("Clear");
        btn_Search_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Search_ClearActionPerformed(evt);
            }
        });
        jPanel3.add(btn_Search_Clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 112, 43));

        lbl_maNhaCC_Search_Hint.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lbl_maNhaCC_Search_Hint.setForeground(new java.awt.Color(204, 0, 0));
        lbl_maNhaCC_Search_Hint.setText("  Invalid!");
        jPanel3.add(lbl_maNhaCC_Search_Hint, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 100, 20));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("Phone Number");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 147, 124, -1));

        txt_Search_sdt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel3.add(txt_Search_sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 220, 30));

        lbl_sdt_Search_Hint.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lbl_sdt_Search_Hint.setForeground(new java.awt.Color(204, 0, 0));
        lbl_sdt_Search_Hint.setText("  Invalid!");
        jPanel3.add(lbl_sdt_Search_Hint, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 172, 100, 20));

        jPanel1.add(jPanel3);
        jPanel3.setBounds(850, 40, 380, 300);

        lbl_maNhaCC_Hint.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lbl_maNhaCC_Hint.setForeground(new java.awt.Color(204, 51, 0));
        lbl_maNhaCC_Hint.setText("  Invalid!");
        jPanel1.add(lbl_maNhaCC_Hint);
        lbl_maNhaCC_Hint.setBounds(170, 60, 120, 20);

        jLabel18.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel18.setText("(*) required fields");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(40, 360, 113, 26);

        lbl_sdt_Hint.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lbl_sdt_Hint.setForeground(new java.awt.Color(204, 51, 0));
        lbl_sdt_Hint.setText("  Invalid!");
        jPanel1.add(lbl_sdt_Hint);
        lbl_sdt_Hint.setBounds(170, 190, 120, 20);

        txt_SDT.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txt_SDT);
        txt_SDT.setBounds(170, 150, 410, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/11111.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(6, 19, 1260, 402);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Supplier List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        tab_NhaCungCap.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        tab_NhaCungCap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab_NhaCungCap.getTableHeader().setReorderingAllowed(false);
        tab_NhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_NhaCungCapMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab_NhaCungCap);
        if (tab_NhaCungCap.getColumnModel().getColumnCount() > 0) {
            tab_NhaCungCap.getColumnModel().getColumn(0).setResizable(false);
            tab_NhaCungCap.getColumnModel().getColumn(1).setResizable(false);
            tab_NhaCungCap.getColumnModel().getColumn(2).setResizable(false);
            tab_NhaCungCap.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1261, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
        );

        btn_ListKH.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_ListKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-view-calendar-list-icon.png"))); // NOI18N
        btn_ListKH.setText("List");
        btn_ListKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ListKHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_ListKH, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ListKH, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tab_NhaCungCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_NhaCungCapMouseClicked

        lbl_sdt_Hint.setVisible(false);
        lbl_maNhaCC_Hint.setVisible(false);
        lbl_sdt_Search_Hint.setVisible(false);
        lbl_maNhaCC_Search_Hint.setVisible(false);
        int row = tab_NhaCungCap.getSelectedRow();
        Integer maNhaCungCap = (Integer) tab_NhaCungCap.getValueAt(row, 0);
        String tenNhaCungCap = (String) tab_NhaCungCap.getValueAt(row, 1);
        Integer sdt = (Integer) tab_NhaCungCap.getValueAt(row, 2);
        String email = (String) tab_NhaCungCap.getValueAt(row, 3);
        String diaChi = (String) tab_NhaCungCap.getValueAt(row, 4);
        txt_MaNhaCC.setText(maNhaCungCap.toString());
        txt_TenNCC.setText(tenNhaCungCap);
        txt_SDT.setText(sdt.toString());
        txt_Email.setText(email);
        txt_DiaChi.setText(diaChi);
        txt_MaNhaCC.setEnabled(false);
        btnThem.setEnabled(false);

    }//GEN-LAST:event_tab_NhaCungCapMouseClicked

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        xoaTrang();
        lbl_sdt_Search_Hint.setVisible(false);
        lbl_maNhaCC_Search_Hint.setVisible(false);
        //khởi tạo lại model, xóa hết cột cũ dòng cũ đi
        tableModel = new DefaultTableModel();
        //tạo cột
        tableModel.addColumn("Supplier No.");
        tableModel.addColumn("Supplier Name");
        tableModel.addColumn("Phone Number");
        tableModel.addColumn("Email");
        tableModel.addColumn("Address");
        NhaCungCapDAO nhaCungCapDAO = new NhaCungCapDAO();
        //lấy ra thông tin tìm kiếm
        NhaCungCap ncc = new NhaCungCap();
        if (txt_Search_TenNhaCC.getText().trim().equals("") && txt_Search_NCC_ID.getText().trim().equals("")
                && txt_Search_sdt.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Enter information into the search box!");
            return;
        }
        if (!txt_Search_NCC_ID.getText().trim().equals("")) {
            while (true) {
                try {
                    Integer.parseInt(txt_Search_NCC_ID.getText().trim());
                    lbl_maNhaCC_Search_Hint.setVisible(false);
                    break;
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Invalid!! \n"
                            + "Some fields are not allowed to contain letters or special characters");
                    lbl_maNhaCC_Search_Hint.setVisible(true);
                    return;
                }
            }
        }
        if (!txt_Search_sdt.getText().trim().equals("")) {
            while (true) {
                try {
                    Integer.parseInt(txt_Search_sdt.getText().trim());
                    lbl_sdt_Search_Hint.setVisible(false);
                    break;
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Invalid!! \n"
                            + "Some fields are not allowed to contain letters or special characters");
                    lbl_sdt_Search_Hint.setVisible(true);
                    return;
                }
            }
        }
        ncc.setTenNhaCC(txt_Search_TenNhaCC.getText().trim());
        if (!txt_Search_NCC_ID.getText().trim().equals("")) {
            ncc.setMaNhaCC(Integer.parseInt(txt_Search_NCC_ID.getText().trim()));
        }
        if (!txt_Search_sdt.getText().trim().equals("")) {
            ncc.setSdt(Integer.parseInt(txt_Search_sdt.getText().trim()));
        }

        List<NhaCungCap> nhaCungCapList = nhaCungCapDAO.search(ncc);
        for (NhaCungCap ncco : nhaCungCapList) {
            Vector vector = new Vector();
            vector.add(ncco.getMaNhaCC());
            vector.add(ncco.getTenNhaCC());
            vector.add(ncco.getSdt());
            vector.add(ncco.getEmail());
            vector.add(ncco.getDiaChi());
            //tạo hàng
            tableModel.addRow(vector);
        }
        //đưa dữ liệu từ model vào bảng
        tab_NhaCungCap.setModel(tableModel);

    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnXoaTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTrangActionPerformed
        xoaTrang();
        xoaTrangSearch();
    }//GEN-LAST:event_btnXoaTrangActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int row = tab_NhaCungCap.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select one Supplier before deleting !");
            return;
        }
        Integer maNhaCungCap = (Integer) tab_NhaCungCap.getValueAt(row, 0);
        if ((new SanPhamDAO()).getListMaNhaCC().contains(maNhaCungCap)) {
            JOptionPane.showMessageDialog(this, "Unable to remove this Supplier information\n"
                    + "Product of this Supplier is still available!");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete??", "Warning", OK_CANCEL_OPTION);
        //Nếu chọn Yes
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                NhaCungCapDAO nccDAO = new NhaCungCapDAO();
                NhaCungCap ncc = new NhaCungCap(maNhaCungCap);
                nccDAO.delete(ncc);
                xoaTrang();
                xoaTrangSearch();
                loadDataIntoTable_NhaCC();
                JOptionPane.showMessageDialog(this, "Supplier information removed !");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(FormNhaCungCap.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(FormNhaCungCap.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed

        try {
            //kiêm tra các thông tin bắt buộc nhập là quyền và tên vai trò
            if (txt_MaNhaCC.getText().isEmpty() || txt_TenNCC.getText().isEmpty() || txt_SDT.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill in all required fields(*) in the Information box");
                lbl_maNhaCC_Hint.setVisible(false);
                lbl_sdt_Hint.setVisible(false);
                return;
            }

            while (true) {
                try {
                    while (true) {
                        try {
                            Integer.parseInt(txt_MaNhaCC.getText().trim());
                            lbl_maNhaCC_Hint.setVisible(false);
                            break;
                        } catch (NumberFormatException e) {
                            lbl_maNhaCC_Hint.setVisible(true);
                            break;
                        }
                    }
                    while (true) {
                        try {
                            Integer.parseInt(txt_SDT.getText().trim());
                            lbl_sdt_Hint.setVisible(false);
                            break;
                        } catch (NumberFormatException e) {
                            lbl_sdt_Hint.setVisible(true);
                            break;
                        }
                    }
                    Integer.parseInt(txt_MaNhaCC.getText().trim());
                    Integer.parseInt(txt_SDT.getText().trim());
                    break;
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Invalid!! \n"
                            + "Some fields are not allowed to contain letters or special characters");
                    return;
                }
            }
            NhaCungCapDAO nhaCungCapDAO = new NhaCungCapDAO();
            if (nhaCungCapDAO.getListMaNhaCungCap().contains(Integer.parseInt(txt_MaNhaCC.getText().trim()))) {
                JOptionPane.showMessageDialog(this, "Supplier Number already exists!\n"
                        + "Re-Enter the Supplier Number!!");
                txt_MaNhaCC.setText("");
                return;
            }
            //lấy giá trị nhập trên form truyền vào đôi tượng
            NhaCungCap ncc = new NhaCungCap();
            ncc.setMaNhaCC(Integer.parseInt(txt_MaNhaCC.getText()));
            ncc.setTenNhaCC(txt_TenNCC.getText());
            ncc.setSdt(Integer.parseInt(txt_SDT.getText()));
            ncc.setEmail(txt_Email.getText());
            ncc.setDiaChi(txt_DiaChi.getText());
            //thực hiện thêm vào DB
            nhaCungCapDAO.insert(ncc);

            //reset form
            xoaTrang();
            xoaTrangSearch();
            //load lại dữ liệu lên lưới
            loadDataIntoTable_NhaCC();
            //nếu thành công thì thông báo
            JOptionPane.showMessageDialog(this, "Successfully add new Supplier !");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FormNhaCungCap.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FormNhaCungCap.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int row = tab_NhaCungCap.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Select one Supplier before updating!");
            return;
        }
        try {
            //kiêm tra các thông tin bắt buộc nhập là quyền và tên vai trò
            if (txt_TenNCC.getText().isEmpty() || txt_SDT.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill in all required fields(*) in the Information box");
                lbl_sdt_Hint.setVisible(false);
                return;
            }
            while (true) {
                try {
                    Integer.parseInt(txt_SDT.getText().trim());
                    lbl_sdt_Hint.setVisible(false);
                    break;
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Invalid!! \n"
                            + "Some fields are not allowed to contain letters or special characters");
                    lbl_sdt_Hint.setVisible(true);
                    return;
                }
            }
            if (soSanh(row)) {
                JOptionPane.showMessageDialog(this, "All of the informations are retainded!!");
                return;
            }
            NhaCungCapDAO nhaCungCapDAO = new NhaCungCapDAO();
            //lấy giá trị nhập trên form truyền vào đôi tượng
            NhaCungCap ncco = new NhaCungCap();
            ncco.setMaNhaCC(Integer.parseInt(txt_MaNhaCC.getText().trim()));
            ncco.setTenNhaCC(txt_TenNCC.getText());
            ncco.setSdt(Integer.parseInt(txt_SDT.getText().trim()));
            ncco.setDiaChi(txt_DiaChi.getText());
            ncco.setEmail(txt_Email.getText().trim());
            //thực hiện thêm vào DB
            nhaCungCapDAO.update(ncco);
            //nếu thành công thì thông báo
            JOptionPane.showMessageDialog(this, "Supplier information updated successfully !");
            //reset form
            xoaTrang();
            xoaTrangSearch();
            //load lại dữ liệu lên lưới
            loadDataIntoTable_NhaCC();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FormNhaCungCap.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FormNhaCungCap.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSuaActionPerformed

    private void btn_Search_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Search_ClearActionPerformed
        // TODO add your handling code here:
        txt_Search_TenNhaCC.setText("");
        txt_Search_NCC_ID.setText("");
        txt_Search_sdt.setText("");
    }//GEN-LAST:event_btn_Search_ClearActionPerformed

    private void btn_ListKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ListKHActionPerformed
        try {
            // TODO add your handling code here:
            loadDataIntoTable_NhaCC();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FormNhaCungCap.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(FormNhaCungCap.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_ListKHActionPerformed

    private void xoaTrang() {
        txt_MaNhaCC.setText("");
        txt_MaNhaCC.setEnabled(true);
        txt_TenNCC.setText("");
        txt_SDT.setText("");
        txt_DiaChi.setText("");
        txt_Email.setText("");
        btnThem.setEnabled(true);
        tab_NhaCungCap.clearSelection();
        lbl_maNhaCC_Hint.setVisible(false);
        lbl_sdt_Hint.setVisible(false);
    }

    private void xoaTrangSearch() {
        txt_Search_NCC_ID.setText("");
        txt_Search_TenNhaCC.setText("");
        txt_Search_sdt.setText("");
        lbl_maNhaCC_Search_Hint.setVisible(false);
        lbl_sdt_Search_Hint.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and dincclay the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FormNhaCungCap().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(FormNhaCungCap.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(FormNhaCungCap.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaTrang;
    private javax.swing.JButton btn_ListKH;
    private javax.swing.JButton btn_Search_Clear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_maNhaCC_Hint;
    private javax.swing.JLabel lbl_maNhaCC_Search_Hint;
    private javax.swing.JLabel lbl_sdt_Hint;
    private javax.swing.JLabel lbl_sdt_Search_Hint;
    private javax.swing.JTable tab_NhaCungCap;
    private javax.swing.JTextField txt_DiaChi;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_MaNhaCC;
    private javax.swing.JTextField txt_SDT;
    private javax.swing.JTextField txt_Search_NCC_ID;
    private javax.swing.JTextField txt_Search_TenNhaCC;
    private javax.swing.JTextField txt_Search_sdt;
    private javax.swing.JTextField txt_TenNCC;
    // End of variables declaration//GEN-END:variables

    public boolean soSanh(int row) {
        Integer maNhaCungCap = (Integer) tab_NhaCungCap.getValueAt(row, 0);
        NhaCungCap ncc = (new NhaCungCapDAO()).getNhaCungCapByID(maNhaCungCap);
        String tenNhaCungCap = txt_TenNCC.getText().trim();
        Integer sdt = txt_SDT.getText().trim().equals(ncc.getSdt().toString())
                ? Integer.parseInt(txt_SDT.getText().trim()) : (new Random()).nextInt();
        String email = txt_Email.getText().trim();
        String diaChi = txt_DiaChi.getText().trim();
        if (ncc.getTenNhaCC().equals(tenNhaCungCap) && ncc.getSdt().equals(sdt) && ncc.getDiaChi().equals(diaChi)
                && ncc.getEmail().trim().equals(email)) {
            return true;
        }
        return false;
    }
}
